FROM python:3.12

WORKDIR /ID

RUN pip install poetry==1.8.3

# Cache packages, they don't change often
COPY poetry.lock pyproject.toml ./
RUN poetry config virtualenvs.create false && poetry install --no-interaction --no-ansi

COPY . .

CMD uvicorn web.main:app --host 0.0.0.0 --port 80 --reload
