services:
    solver:
        restart: always
        ports:
            - "80:80"
        env_file:
            - env/jwt.env
            - env/database.env
        build:
            context: ./
            dockerfile: Dockerfile-dev
        volumes:
            - ./:/ID
        depends_on:
            - db


    db:
        image: postgres:latest
        restart: always
        env_file:
            - env/database.env
        volumes:
            - postgres-volume:/var/lib/postgresql/data
            - ./SQL/create_all.sql:/docker-entrypoint-initdb.d/init.sql
        logging:
            driver: none
volumes:
    postgres-volume:
