INSERT INTO educational_certificates_types (id, prerequirement, name) VALUES (1, null,$$Certificate of Participation/Completion$$);
INSERT INTO educational_certificates_types (id, prerequirement, name) VALUES (2, 1, $$High School Diploma or Equivalent (e.g., GED)$$);
INSERT INTO educational_certificates_types (id, prerequirement, name) VALUES (3, 1, $$Vocational or Technical Certificates$$);
INSERT INTO educational_certificates_types (id, prerequirement, name) VALUES (4, 2, $$Associate Degree$$);
INSERT INTO educational_certificates_types (id, prerequirement, name) VALUES (5, 2, $$Bachelor's Degree$$);
INSERT INTO educational_certificates_types (id, prerequirement, name) VALUES (6, 3, $$Graduate Certificates$$);
INSERT INTO educational_certificates_types (id, prerequirement, name) VALUES (7, 3, $$Master's Degree$$);
INSERT INTO educational_certificates_types (id, prerequirement, name) VALUES (8, 4, $$Professional Degrees$$);
INSERT INTO educational_certificates_types (id, prerequirement, name) VALUES (9, 4, $$Doctoral Degree (Ph.D.)$$);
INSERT INTO educational_certificates_types (id, prerequirement, name) VALUES (10, 5, $$Post-Doctoral Certifications/Fellowships$$);
