INSERT INTO educational_instances (id, name, location, creation_date, kind) VALUES (1, $$Harvard University$$, $$USA-Cambridge$$, $$1636-09-08$$, 2);
INSERT INTO educational_instances (id, name, location, creation_date, kind) VALUES (2, $$Stanford University$$, $$USA-Stanford$$, $$1885-10-01$$, 2);
INSERT INTO educational_instances (id, name, location, creation_date, kind) VALUES (3, $$Massachusetts Institute of Technology$$, $$USA-Cambridge$$, $$1861-04-10$$, 2);
INSERT INTO educational_instances (id, name, location, creation_date, kind) VALUES (4, $$University of California, Berkeley$$, $$USA-Berkeley$$, $$1868-03-23$$, 2);
INSERT INTO educational_instances (id, name, location, creation_date, kind) VALUES (5, $$California Institute of Technology$$, $$USA-Pasadena$$, $$1891-09-23$$, 2);
INSERT INTO educational_instances (id, name, location, creation_date, kind) VALUES (6, $$University of Oxford$$, $$UK-Oxford$$, $$1096-01-01$$, 2);
INSERT INTO educational_instances (id, name, location, creation_date, kind) VALUES (7, $$University of Cambridge$$, $$UK-Cambridge$$, $$1209-01-01$$, 2);
INSERT INTO educational_instances (id, name, location, creation_date, kind) VALUES (8, $$Princeton University$$, $$USA-Princeton$$, $$1746-10-22$$, 2);
INSERT INTO educational_instances (id, name, location, creation_date, kind) VALUES (9, $$Yale University$$, $$USA-New Haven$$, $$1701-10-09$$, 2);
INSERT INTO educational_instances (id, name, location, creation_date, kind) VALUES (10, $$University of Chicago$$, $$USA-Chicago$$, $$1890-07-09$$, 2);
INSERT INTO educational_instances (id, name, location, creation_date, kind) VALUES (11, $$Columbia University$$, $$USA-New York$$, $$1754-05-25$$, 2);
INSERT INTO educational_instances (id, name, location, creation_date, kind) VALUES (12, $$University of Pennsylvania$$, $$USA-Philadelphia$$, $$1740-11-14$$, 2);
INSERT INTO educational_instances (id, name, location, creation_date, kind) VALUES (13, $$University of Michigan$$, $$USA-Ann Arbor$$, $$1817-08-26$$, 2);
INSERT INTO educational_instances (id, name, location, creation_date, kind) VALUES (14, $$Johns Hopkins University$$, $$USA-Baltimore$$, $$1876-02-22$$, 2);
INSERT INTO educational_instances (id, name, location, creation_date, kind) VALUES (15, $$University of California, Los Angeles$$, $$USA-Los Angeles$$, $$1919-05-23$$, 2);
INSERT INTO educational_instances (id, name, location, creation_date, kind) VALUES (16, $$Duke University$$, $$USA-Durham$$, $$1838-12-28$$, 2);
INSERT INTO educational_instances (id, name, location, creation_date, kind) VALUES (17, $$Northwestern University$$, $$USA-Evanston$$, $$1851-01-28$$, 2);
INSERT INTO educational_instances (id, name, location, creation_date, kind) VALUES (18, $$New York University$$, $$USA-New York$$, $$1831-04-21$$, 2);
INSERT INTO educational_instances (id, name, location, creation_date, kind) VALUES (19, $$University of California, San Diego$$, $$USA-San Diego$$, $$1960-11-18$$, 2);
INSERT INTO educational_instances (id, name, location, creation_date, kind) VALUES (20, $$University of Washington$$, $$USA-Seattle$$, $$1861-11-04$$, 2);
INSERT INTO educational_instances (id, name, location, creation_date, kind) VALUES (21, $$University of Toronto$$, $$Canada-Toronto$$, $$1827-03-15$$, 2);
INSERT INTO educational_instances (id, name, location, creation_date, kind) VALUES (22, $$Imperial College London$$, $$UK-London$$, $$1907-07-08$$, 2);
INSERT INTO educational_instances (id, name, location, creation_date, kind) VALUES (23, $$University College London$$, $$UK-London$$, $$1826-02-11$$, 2);
INSERT INTO educational_instances (id, name, location, creation_date, kind) VALUES (24, $$University of Edinburgh$$, $$UK-Edinburgh$$, $$1582-04-14$$, 2);
INSERT INTO educational_instances (id, name, location, creation_date, kind) VALUES (25, $$University of Melbourne$$, $$Australia-Melbourne$$, $$1853-04-11$$, 2);
INSERT INTO educational_instances (id, name, location, creation_date, kind) VALUES (26, $$Australian National University$$, $$Australia-Canberra$$, $$1946-08-01$$, 2);
INSERT INTO educational_instances (id, name, location, creation_date, kind) VALUES (27, $$University of Sydney$$, $$Australia-Sydney$$, $$1850-10-01$$, 2);
INSERT INTO educational_instances (id, name, location, creation_date, kind) VALUES (28, $$University of Queensland$$, $$Australia-Brisbane$$, $$1909-12-16$$, 2);
INSERT INTO educational_instances (id, name, location, creation_date, kind) VALUES (29, $$London School of Economics and Political Science$$, $$UK-London$$, $$1895-10-10$$, 2);
INSERT INTO educational_instances (id, name, location, creation_date, kind) VALUES (30, $$University of Hong Kong$$, $$Hong Kong-Hong Kong$$, $$1911-03-30$$, 2);
INSERT INTO educational_instances (id, name, location, creation_date, kind) VALUES (31, $$National University of Singapore$$, $$Singapore-Singapore$$, $$1905-08-03$$, 2);
INSERT INTO educational_instances (id, name, location, creation_date, kind) VALUES (32, $$ETH Zurich$$, $$Switzerland-Zurich$$, $$1855-10-16$$, 2);
INSERT INTO educational_instances (id, name, location, creation_date, kind) VALUES (33, $$Peking University$$, $$China-Beijing$$, $$1898-12-17$$, 2);
INSERT INTO educational_instances (id, name, location, creation_date, kind) VALUES (34, $$Tsinghua University$$, $$China-Beijing$$, $$1911-04-29$$, 2);
INSERT INTO educational_instances (id, name, location, creation_date, kind) VALUES (35, $$University of British Columbia$$, $$Canada-Vancouver$$, $$1908-09-30$$, 2);
INSERT INTO educational_instances (id, name, location, creation_date, kind) VALUES (36, $$University of Tokyo$$, $$Japan-Tokyo$$, $$1877-04-12$$, 2);
INSERT INTO educational_instances (id, name, location, creation_date, kind) VALUES (37, $$Seoul National University$$, $$South Korea-Seoul$$, $$1946-08-22$$, 2);
INSERT INTO educational_instances (id, name, location, creation_date, kind) VALUES (38, $$McGill University$$, $$Canada-Montreal$$, $$1821-03-31$$, 2);
INSERT INTO educational_instances (id, name, location, creation_date, kind) VALUES (39, $$University of Manchester$$, $$UK-Manchester$$, $$1824-10-22$$, 2);
INSERT INTO educational_instances (id, name, location, creation_date, kind) VALUES (40, $$University of Wisconsin-Madison$$, $$USA-Madison$$, $$1848-07-26$$, 2);
INSERT INTO educational_instances (id, name, location, creation_date, kind) VALUES (41, $$Cornell University$$, $$USA-Ithaca$$, $$1865-04-27$$, 2);
INSERT INTO educational_instances (id, name, location, creation_date, kind) VALUES (42, $$University of California, Davis$$, $$USA-Davis$$, $$1905-03-18$$, 2);
INSERT INTO educational_instances (id, name, location, creation_date, kind) VALUES (43, $$University of Illinois at Urbana-Champaign$$, $$USA-Champaign$$, $$1867-03-02$$, 2);
INSERT INTO educational_instances (id, name, location, creation_date, kind) VALUES (44, $$Carnegie Mellon University$$, $$USA-Pittsburgh$$, $$1900-11-15$$, 2);
INSERT INTO educational_instances (id, name, location, creation_date, kind) VALUES (45, $$University of Texas at Austin$$, $$USA-Austin$$, $$1883-09-15$$, 2);
INSERT INTO educational_instances (id, name, location, creation_date, kind) VALUES (46, $$University of Southern California$$, $$USA-Los Angeles$$, $$1880-10-06$$, 2);
INSERT INTO educational_instances (id, name, location, creation_date, kind) VALUES (47, $$King's College London$$, $$UK-London$$, $$1829-08-14$$, 2);
INSERT INTO educational_instances (id, name, location, creation_date, kind) VALUES (48, $$University of North Carolina at Chapel Hill$$, $$USA-Chapel Hill$$, $$1789-12-11$$, 2);
INSERT INTO educational_instances (id, name, location, creation_date, kind) VALUES (49, $$University of Minnesota$$, $$USA-Minneapolis$$, $$1851-02-25$$, 2);
INSERT INTO educational_instances (id, name, location, creation_date, kind) VALUES (50, $$Monash University$$, $$Australia-Melbourne$$, $$1958-06-27$$, 2);
INSERT INTO educational_instances (id, name, location, creation_date, kind) VALUES (51, $$Kyoto University$$, $$Japan-Kyoto$$, $$1897-06-18$$, 2);
INSERT INTO educational_instances (id, name, location, creation_date, kind) VALUES (52, $$University of Glasgow$$, $$UK-Glasgow$$, $$1451-01-07$$, 2);
INSERT INTO educational_instances (id, name, location, creation_date, kind) VALUES (53, $$University of Birmingham$$, $$UK-Birmingham$$, $$1900-03-09$$, 2);
INSERT INTO educational_instances (id, name, location, creation_date, kind) VALUES (54, $$University of Bristol$$, $$UK-Bristol$$, $$1876-07-10$$, 2);
INSERT INTO educational_instances (id, name, location, creation_date, kind) VALUES (55, $$University of Southampton$$, $$UK-Southampton$$, $$1862-06-29$$, 2);
INSERT INTO educational_instances (id, name, location, creation_date, kind) VALUES (56, $$University of Warwick$$, $$UK-Coventry$$, $$1965-10-01$$, 2);
INSERT INTO educational_instances (id, name, location, creation_date, kind) VALUES (57, $$University of Sheffield$$, $$UK-Sheffield$$, $$1905-05-31$$, 2);
INSERT INTO educational_instances (id, name, location, creation_date, kind) VALUES (58, $$University of Leeds$$, $$UK-Leeds$$, $$1904-06-06$$, 2);
INSERT INTO educational_instances (id, name, location, creation_date, kind) VALUES (59, $$University of Nottingham$$, $$UK-Nottingham$$, $$1881-06-17$$, 2);
INSERT INTO educational_instances (id, name, location, creation_date, kind) VALUES (60, $$University of Exeter$$, $$UK-Exeter$$, $$1955-07-24$$, 2);
INSERT INTO educational_instances (id, name, location, creation_date, kind) VALUES (61, $$University of St Andrews$$, $$UK-St Andrews$$, $$1413-02-28$$, 2);
INSERT INTO educational_instances (id, name, location, creation_date, kind) VALUES (62, $$University of Liverpool$$, $$UK-Liverpool$$, $$1881-07-16$$, 2);
INSERT INTO educational_instances (id, name, location, creation_date, kind) VALUES (63, $$University of York$$, $$UK-York$$, $$1963-10-09$$, 2);
INSERT INTO educational_instances (id, name, location, creation_date, kind) VALUES (64, $$Durham University$$, $$UK-Durham$$, $$1832-08-01$$, 2);
INSERT INTO educational_instances (id, name, location, creation_date, kind) VALUES (65, $$University of Aberdeen$$, $$UK-Aberdeen$$, $$1495-09-10$$, 2);
INSERT INTO educational_instances (id, name, location, creation_date, kind) VALUES (66, $$University of Dundee$$, $$UK-Dundee$$, $$1881-07-25$$, 2);
INSERT INTO educational_instances (id, name, location, creation_date, kind) VALUES (67, $$University of East Anglia$$, $$UK-Norwich$$, $$1963-11-01$$, 2);
INSERT INTO educational_instances (id, name, location, creation_date, kind) VALUES (68, $$University of Reading$$, $$UK-Reading$$, $$1892-03-17$$, 2);
INSERT INTO educational_instances (id, name, location, creation_date, kind) VALUES (69, $$University of Surrey$$, $$UK-Guildford$$, $$1966-09-22$$, 2);
INSERT INTO educational_instances (id, name, location, creation_date, kind) VALUES (70, $$University of Sussex$$, $$UK-Falmer$$, $$1961-08-16$$, 2);
INSERT INTO educational_instances (id, name, location, creation_date, kind) VALUES (71, $$University of Leicester$$, $$UK-Leicester$$, $$1921-07-20$$, 2);
INSERT INTO educational_instances (id, name, location, creation_date, kind) VALUES (72, $$Queen Mary University of London$$, $$UK-London$$, $$1887-10-11$$, 2);
INSERT INTO educational_instances (id, name, location, creation_date, kind) VALUES (73, $$City, University of London$$, $$UK-London$$, $$1894-05-14$$, 2);
INSERT INTO educational_instances (id, name, location, creation_date, kind) VALUES (74, $$Royal Holloway, University of London$$, $$UK-Egham$$, $$1849-06-30$$, 2);
INSERT INTO educational_instances (id, name, location, creation_date, kind) VALUES (75, $$Birkbeck, University of London$$, $$UK-London$$, $$1823-06-02$$, 2);
INSERT INTO educational_instances (id, name, location, creation_date, kind) VALUES (76, $$School of Oriental and African Studies$$, $$UK-London$$, $$1916-06-05$$, 2);
INSERT INTO educational_instances (id, name, location, creation_date, kind) VALUES (77, $$Goldsmiths, University of London$$, $$UK-London$$, $$1904-01-29$$, 2);
INSERT INTO educational_instances (id, name, location, creation_date, kind) VALUES (78, $$University of Strathclyde$$, $$UK-Glasgow$$, $$1796-07-01$$, 2);
INSERT INTO educational_instances (id, name, location, creation_date, kind) VALUES (79, $$Heriot-Watt University$$, $$UK-Edinburgh$$, $$1821-10-16$$, 2);
INSERT INTO educational_instances (id, name, location, creation_date, kind) VALUES (80, $$University of Kent$$, $$UK-Canterbury$$, $$1965-01-04$$, 2);
INSERT INTO educational_instances (id, name, location, creation_date, kind) VALUES (81, $$Loughborough University$$, $$UK-Loughborough$$, $$1909-07-18$$, 2);
INSERT INTO educational_instances (id, name, location, creation_date, kind) VALUES (82, $$University of Bath$$, $$UK-Bath$$, $$1966-10-25$$, 2);
INSERT INTO educational_instances (id, name, location, creation_date, kind) VALUES (83, $$University of Essex$$, $$UK-Colchester$$, $$1964-09-11$$, 2);
INSERT INTO educational_instances (id, name, location, creation_date, kind) VALUES (84, $$Lancaster University$$, $$UK-Lancaster$$, $$1964-08-20$$, 2);
INSERT INTO educational_instances (id, name, location, creation_date, kind) VALUES (85, $$Swansea University$$, $$UK-Swansea$$, $$1920-05-19$$, 2);
INSERT INTO educational_instances (id, name, location, creation_date, kind) VALUES (86, $$Cardiff University$$, $$UK-Cardiff$$, $$1883-10-24$$, 2);
INSERT INTO educational_instances (id, name, location, creation_date, kind) VALUES (87, $$University of Plymouth$$, $$UK-Plymouth$$, $$1862-04-10$$, 2);
INSERT INTO educational_instances (id, name, location, creation_date, kind) VALUES (88, $$University of Portsmouth$$, $$UK-Portsmouth$$, $$1992-07-07$$, 2);
INSERT INTO educational_instances (id, name, location, creation_date, kind) VALUES (89, $$University of Hull$$, $$UK-Hull$$, $$1927-10-11$$, 2);
INSERT INTO educational_instances (id, name, location, creation_date, kind) VALUES (90, $$Aberystwyth University$$, $$UK-Aberystwyth$$, $$1872-10-15$$, 2);
INSERT INTO educational_instances (id, name, location, creation_date, kind) VALUES (91, $$Bangor University$$, $$UK-Bangor$$, $$1884-10-18$$, 2);
INSERT INTO educational_instances (id, name, location, creation_date, kind) VALUES (92, $$University of Lincoln$$, $$UK-Lincoln$$, $$1861-02-14$$, 2);
INSERT INTO educational_instances (id, name, location, creation_date, kind) VALUES (93, $$University of Chester$$, $$UK-Chester$$, $$1839-04-15$$, 2);
INSERT INTO educational_instances (id, name, location, creation_date, kind) VALUES (94, $$University of Huddersfield$$, $$UK-Huddersfield$$, $$1825-08-18$$, 2);
INSERT INTO educational_instances (id, name, location, creation_date, kind) VALUES (95, $$University of Brighton$$, $$UK-Brighton$$, $$1859-07-10$$, 2);
INSERT INTO educational_instances (id, name, location, creation_date, kind) VALUES (96, $$University of Central Lancashire$$, $$UK-Preston$$, $$1828-09-20$$, 2);
INSERT INTO educational_instances (id, name, location, creation_date, kind) VALUES (97, $$University of Westminster$$, $$UK-London$$, $$1838-08-11$$, 2);
INSERT INTO educational_instances (id, name, location, creation_date, kind) VALUES (98, $$Phillips Exeter Academy$$, $$USA-Exeter$$, $$1781-04-03$$, 2);
INSERT INTO educational_instances (id, name, location, creation_date, kind) VALUES (99, $$Eton College$$, $$UK-Windsor$$, $$1440-06-12$$, 2);
INSERT INTO educational_instances (id, name, location, creation_date, kind) VALUES (100, $$Choate Rosemary Hall$$, $$USA-Wallingford$$, $$1890-10-24$$, 2);
INSERT INTO educational_instances (id, name, location, creation_date, kind) VALUES (101, $$Andover Phillips Academy$$, $$USA-Andover$$, $$1778-04-21$$, 2);
INSERT INTO educational_instances (id, name, location, creation_date, kind) VALUES (102, $$Rugby School$$, $$UK-Rugby$$, $$1567-09-01$$, 2);
INSERT INTO educational_instances (id, name, location, creation_date, kind) VALUES (103, $$The Lawrenceville School$$, $$USA-Lawrenceville$$, $$1810-06-15$$, 2);
