INSERT INTO educational_instances (id, name, address, creation_date, country, city) VALUES (1, $$University of Warsaw$$, $$Krakowskie Przedmieście 26/28, 00-927 Warsaw$$, $$1816-11-19$$, $$Poland$$, $$Warsaw$$);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (4, 1);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (5, 1);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (6, 1);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (7, 1);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (8, 1);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (9, 1);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (10, 1);
INSERT INTO educational_instances (id, name, address, creation_date, country, city) VALUES (2, $$Jagiellonian University$$, $$Golebia 24, 31-007 Krakow$$, $$1364-05-12$$, $$Poland$$, $$Krakow$$);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (4, 2);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (5, 2);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (6, 2);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (7, 2);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (8, 2);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (9, 2);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (10, 2);
INSERT INTO educational_instances (id, name, address, creation_date, country, city) VALUES (3, $$Adam Mickiewicz University$$, $$ul. Henryka Wieniawskiego 1, 61-712 Poznan$$, $$1919-05-07$$, $$Poland$$, $$Poznan$$);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (4, 3);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (5, 3);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (6, 3);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (7, 3);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (8, 3);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (9, 3);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (10, 3);
INSERT INTO educational_instances (id, name, address, creation_date, country, city) VALUES (4, $$AGH University of Science and Technology$$, $$al. Mickiewicza 30, 30-059 Krakow$$, $$1919-04-20$$, $$Poland$$, $$Krakow$$);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (4, 4);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (5, 4);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (6, 4);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (7, 4);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (8, 4);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (9, 4);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (10, 4);
INSERT INTO educational_instances (id, name, address, creation_date, country, city) VALUES (5, $$Warsaw University of Technology$$, $$Plac Politechniki 1, 00-661 Warsaw$$, $$1826-01-04$$, $$Poland$$, $$Warsaw$$);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (4, 5);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (5, 5);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (6, 5);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (7, 5);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (8, 5);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (9, 5);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (10, 5);
INSERT INTO educational_instances (id, name, address, creation_date, country, city) VALUES (6, $$University of Wroclaw$$, $$pl. Uniwersytecki 1, 50-137 Wroclaw$$, $$1702-08-01$$, $$Poland$$, $$Wroclaw$$);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (4, 6);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (5, 6);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (6, 6);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (7, 6);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (8, 6);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (9, 6);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (10, 6);
INSERT INTO educational_instances (id, name, address, creation_date, country, city) VALUES (7, $$Gdansk University of Technology$$, $$ul. Narutowicza 11/12, 80-233 Gdansk$$, $$1904-10-06$$, $$Poland$$, $$Gdansk$$);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (4, 7);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (5, 7);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (6, 7);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (7, 7);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (8, 7);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (9, 7);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (10, 7);
INSERT INTO educational_instances (id, name, address, creation_date, country, city) VALUES (8, $$Lodz University of Technology$$, $$ul. Stefana Żeromskiego 116, 90-924 Lodz$$, $$1945-05-24$$, $$Poland$$, $$Lodz$$);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (4, 8);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (5, 8);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (6, 8);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (7, 8);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (8, 8);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (9, 8);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (10, 8);
INSERT INTO educational_instances (id, name, address, creation_date, country, city) VALUES (9, $$Nicolaus Copernicus University$$, $$ul. Gagarina 11, 87-100 Torun$$, $$1945-10-15$$, $$Poland$$, $$Torun$$);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (4, 9);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (5, 9);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (6, 9);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (7, 9);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (8, 9);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (9, 9);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (10, 9);
INSERT INTO educational_instances (id, name, address, creation_date, country, city) VALUES (10, $$Medical University of Warsaw$$, $$ul. Żwirki i Wigury 61, 02-091 Warsaw$$, $$1950-12-01$$, $$Poland$$, $$Warsaw$$);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (4, 10);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (5, 10);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (6, 10);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (7, 10);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (8, 10);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (9, 10);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (10, 10);
INSERT INTO educational_instances (id, name, address, creation_date, country, city) VALUES (11, $$Harvard University$$, $$Massachusetts Hall, Cambridge, MA 02138$$, $$1636-09-08$$, $$USA$$, $$Cambridge$$);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (4, 11);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (5, 11);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (6, 11);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (7, 11);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (8, 11);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (9, 11);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (10, 11);
INSERT INTO educational_instances (id, name, address, creation_date, country, city) VALUES (12, $$Stanford University$$, $$450 Serra Mall, Stanford, CA 94305$$, $$1885-11-11$$, $$USA$$, $$Stanford$$);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (4, 12);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (5, 12);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (6, 12);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (7, 12);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (8, 12);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (9, 12);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (10, 12);
INSERT INTO educational_instances (id, name, address, creation_date, country, city) VALUES (13, $$Massachusetts Institute of Technology$$, $$77 Massachusetts Ave, Cambridge, MA 02139$$, $$1861-04-10$$, $$USA$$, $$Cambridge$$);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (4, 13);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (5, 13);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (6, 13);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (7, 13);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (8, 13);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (9, 13);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (10, 13);
INSERT INTO educational_instances (id, name, address, creation_date, country, city) VALUES (14, $$University of California, Berkeley$$, $$200 California Hall, Berkeley, CA 94720$$, $$1868-03-23$$, $$USA$$, $$Berkeley$$);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (4, 14);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (5, 14);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (6, 14);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (7, 14);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (8, 14);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (9, 14);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (10, 14);
INSERT INTO educational_instances (id, name, address, creation_date, country, city) VALUES (15, $$California Institute of Technology$$, $$1200 E California Blvd, Pasadena, CA 91125$$, $$1891-09-23$$, $$USA$$, $$Pasadena$$);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (4, 15);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (5, 15);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (6, 15);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (7, 15);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (8, 15);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (9, 15);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (10, 15);
INSERT INTO educational_instances (id, name, address, creation_date, country, city) VALUES (16, $$University of Chicago$$, $$5801 S Ellis Ave, Chicago, IL 60637$$, $$1890-10-01$$, $$USA$$, $$Chicago$$);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (4, 16);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (5, 16);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (6, 16);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (7, 16);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (8, 16);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (9, 16);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (10, 16);
INSERT INTO educational_instances (id, name, address, creation_date, country, city) VALUES (17, $$Princeton University$$, $$Princeton, NJ 08544$$, $$1746-10-22$$, $$USA$$, $$Princeton$$);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (4, 17);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (5, 17);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (6, 17);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (7, 17);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (8, 17);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (9, 17);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (10, 17);
INSERT INTO educational_instances (id, name, address, creation_date, country, city) VALUES (18, $$Columbia University$$, $$116th St & Broadway, New York, NY 10027$$, $$1754-05-25$$, $$USA$$, $$New York$$);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (4, 18);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (5, 18);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (6, 18);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (7, 18);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (8, 18);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (9, 18);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (10, 18);
INSERT INTO educational_instances (id, name, address, creation_date, country, city) VALUES (19, $$Yale University$$, $$New Haven, CT 06520$$, $$1701-10-09$$, $$USA$$, $$New Haven$$);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (4, 19);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (5, 19);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (6, 19);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (7, 19);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (8, 19);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (9, 19);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (10, 19);
INSERT INTO educational_instances (id, name, address, creation_date, country, city) VALUES (20, $$University of Pennsylvania$$, $$Philadelphia, PA 19104$$, $$1740-11-14$$, $$USA$$, $$Philadelphia$$);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (4, 20);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (5, 20);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (6, 20);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (7, 20);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (8, 20);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (9, 20);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (10, 20);
INSERT INTO educational_instances (id, name, address, creation_date, country, city) VALUES (21, $$John Paul II High School$$, $$ul. Swietej Gertrudy 7, 31-046 Krakow$$, $$1957-09-01$$, $$Poland$$, $$Krakow$$);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (1, 21);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (2, 21);
INSERT INTO educational_instances (id, name, address, creation_date, country, city) VALUES (22, $$High School No. 5 Krakow$$, $$ul. Studencka 12, 31-116 Krakow$$, $$1945-09-01$$, $$Poland$$, $$Krakow$$);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (1, 22);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (2, 22);
INSERT INTO educational_instances (id, name, address, creation_date, country, city) VALUES (23, $$International School of Krakow$$, $$ul. Starowislna 26, 31-032 Krakow$$, $$1993-09-01$$, $$Poland$$, $$Krakow$$);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (1, 23);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (2, 23);
INSERT INTO educational_instances (id, name, address, creation_date, country, city) VALUES (24, $$School Complex No. 1 Krakow$$, $$ul. Ulanow 3, 31-450 Krakow$$, $$1964-09-01$$, $$Poland$$, $$Krakow$$);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (1, 24);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (2, 24);
INSERT INTO educational_instances (id, name, address, creation_date, country, city) VALUES (25, $$High School No. 8 Krakow$$, $$ul. Grzegorzecka 24, 31-532 Krakow$$, $$1928-09-01$$, $$Poland$$, $$Krakow$$);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (1, 25);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (2, 25);
INSERT INTO educational_instances (id, name, address, creation_date, country, city) VALUES (26, $$School Complex No. 2 Krakow$$, $$ul. Sobieskiego 15, 31-136 Krakow$$, $$1959-09-01$$, $$Poland$$, $$Krakow$$);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (1, 26);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (2, 26);
INSERT INTO educational_instances (id, name, address, creation_date, country, city) VALUES (27, $$Bilingual High School No. 1 Warsaw$$, $$ul. Syrokomli 20, 30-102 Warsaw$$, $$1992-09-01$$, $$Poland$$, $$Warsaw$$);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (1, 27);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (2, 27);
INSERT INTO educational_instances (id, name, address, creation_date, country, city) VALUES (28, $$Lyceum No. 9 Warsaw$$, $$ul. Nowosadecka 41, 30-383 Warsaw$$, $$1935-09-01$$, $$Poland$$, $$Warsaw$$);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (1, 28);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (2, 28);
INSERT INTO educational_instances (id, name, address, creation_date, country, city) VALUES (29, $$Lyceum No. 3 Warsaw$$, $$ul. Topolowa 22, 31-506 Warsaw$$, $$1910-09-01$$, $$Poland$$, $$Warsaw$$);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (1, 29);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (2, 29);
INSERT INTO educational_instances (id, name, address, creation_date, country, city) VALUES (30, $$Catholic School Complex Warsaw$$, $$ul. Bernardynska 5, 00-055 Warsaw$$, $$1991-09-01$$, $$Poland$$, $$Warsaw$$);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (1, 30);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (2, 30);
INSERT INTO educational_instances (id, name, address, creation_date, country, city) VALUES (31, $$Cracow University of Technology$$, $$ul. Warszawska 24, 31-155 Krakow$$, $$1945-10-06$$, $$Poland$$, $$Krakow$$);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (3, 31);
INSERT INTO educational_instances (id, name, address, creation_date, country, city) VALUES (32, $$AGH University of Science and Technology$$, $$al. Mickiewicza 30, 30-059 Krakow$$, $$1919-04-20$$, $$Poland$$, $$Krakow$$);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (3, 32);
INSERT INTO educational_instances (id, name, address, creation_date, country, city) VALUES (33, $$Warsaw University of Technology$$, $$Plac Politechniki 1, 00-661 Warsaw$$, $$1826-01-04$$, $$Poland$$, $$Warsaw$$);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (3, 33);
INSERT INTO educational_instances (id, name, address, creation_date, country, city) VALUES (34, $$University of Warsaw$$, $$Krakowskie Przedmieście 26/28, 00-927 Warsaw$$, $$1816-11-19$$, $$Poland$$, $$Warsaw$$);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (3, 34);
INSERT INTO educational_instances (id, name, address, creation_date, country, city) VALUES (35, $$University of Social Sciences and Humanities$$, $$ul. Chodakowska 19/31, 03-815 Warsaw$$, $$1996-10-01$$, $$Poland$$, $$Warsaw$$);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (3, 35);
INSERT INTO educational_instances (id, name, address, creation_date, country, city) VALUES (36, $$Warsaw School of Economics$$, $$al. Niepodleglosci 162, 02-554 Warsaw$$, $$1906-10-30$$, $$Poland$$, $$Warsaw$$);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (3, 36);
INSERT INTO educational_instances (id, name, address, creation_date, country, city) VALUES (37, $$University of Information Technology and Management in Rzeszow$$, $$ul. Sucharskiego 2, 35-225 Rzeszow$$, $$1996-11-01$$, $$Poland$$, $$Rzeszow$$);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (3, 37);
INSERT INTO educational_instances (id, name, address, creation_date, country, city) VALUES (38, $$Cracow University of Economics$$, $$ul. Rakowicka 27, 31-510 Krakow$$, $$1925-10-01$$, $$Poland$$, $$Krakow$$);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (3, 38);
INSERT INTO educational_instances (id, name, address, creation_date, country, city) VALUES (39, $$Warsaw University of Life Sciences$$, $$Nowoursynowska 166, 02-787 Warsaw$$, $$1816-09-23$$, $$Poland$$, $$Warsaw$$);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (3, 39);
INSERT INTO educational_instances (id, name, address, creation_date, country, city) VALUES (40, $$Academy of Fine Arts in Warsaw$$, $$Krakowskie Przedmieście 5, 00-068 Warsaw$$, $$1945-10-22$$, $$Poland$$, $$Warsaw$$);
INSERT INTO educational_instances_types_relation (type_id, instance_id) VALUES (3, 40);
