--Offices
INSERT INTO offices (id, office_type, country, address, city) VALUES (1, 'consulat', $$Afghanistan$$, $$Afghanistan Balkh$$, $$Balkh$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (2, 'marriage agency', $$Afghanistan$$, $$Afghanistan Charikar$$, $$Charikar$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (3, 'consulat', $$Albania$$, $$Albania Berat$$, $$Berat$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (4, 'marriage agency', $$Albania$$, $$Albania Burrel$$, $$Burrel$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (5, 'consulat', $$Algeria$$, $$Algeria Adrar$$, $$Adrar$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (6, 'marriage agency', $$Algeria$$, $$Algeria Aflou$$, $$Aflou$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (7, 'consulat', $$Angola$$, $$Angola Benguela$$, $$Benguela$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (8, 'marriage agency', $$Angola$$, $$Angola Cabinda$$, $$Cabinda$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (9, 'consulat', $$Argentina$$, $$Argentina Aguilares$$, $$Aguilares$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (10, 'marriage agency', $$Argentina$$, $$Argentina Alderetes$$, $$Alderetes$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (11, 'consulat', $$Armenia$$, $$Armenia Abovyan$$, $$Abovyan$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (12, 'marriage agency', $$Armenia$$, $$Armenia Ararat$$, $$Ararat$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (13, 'consulat', $$Aruba$$, $$Aruba Angochi$$, $$Angochi$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (14, 'marriage agency', $$Aruba$$, $$Aruba Babijn$$, $$Babijn$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (15, 'consulat', $$Australia$$, $$Australia Adelaide$$, $$Adelaide$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (16, 'marriage agency', $$Australia$$, $$Australia Albany$$, $$Albany$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (17, 'consulat', $$Austria$$, $$Austria Amstetten$$, $$Amstetten$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (18, 'marriage agency', $$Austria$$, $$Austria Ansfelden$$, $$Ansfelden$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (19, 'consulat', $$Azerbaijan$$, $$Azerbaijan Agdzhabedy$$, $$Agdzhabedy$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (20, 'marriage agency', $$Azerbaijan$$, $$Azerbaijan Aghsu$$, $$Aghsu$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (21, 'consulat', $$Bahamas$$, $$Bahamas Freeport$$, $$Freeport$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (22, 'marriage agency', $$Bahamas$$, $$Bahamas Lucaya$$, $$Lucaya$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (23, 'consulat', $$Bahrain$$, $$Bahrain Manama$$, $$Manama$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (24, 'marriage agency', $$Bahrain$$, $$Bahrain Sitrah$$, $$Sitrah$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (25, 'consulat', $$Bangladesh$$, $$Bangladesh Azimpur$$, $$Azimpur$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (26, 'marriage agency', $$Bangladesh$$, $$Bangladesh Badarganj$$, $$Badarganj$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (27, 'consulat', $$Barbados$$, $$Barbados Bridgetown$$, $$Bridgetown$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (28, 'consulat', $$Belarus$$, $$Belarus Asipovichy$$, $$Asipovichy$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (29, 'marriage agency', $$Belarus$$, $$Belarus Babruysk$$, $$Babruysk$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (30, 'consulat', $$Belgium$$, $$Belgium Aalst$$, $$Aalst$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (31, 'marriage agency', $$Belgium$$, $$Belgium Aalter$$, $$Aalter$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (32, 'consulat', $$Belize$$, $$Belize Belmopan$$, $$Belmopan$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (33, 'consulat', $$Benin$$, $$Benin Abomey$$, $$Abomey$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (34, 'marriage agency', $$Benin$$, $$Benin Allada$$, $$Allada$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (35, 'consulat', $$Bermuda$$, $$Bermuda Hamilton$$, $$Hamilton$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (36, 'consulat', $$Bhutan$$, $$Bhutan Phuntsholing$$, $$Phuntsholing$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (37, 'marriage agency', $$Bhutan$$, $$Bhutan Thimphu$$, $$Thimphu$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (38, 'consulat', $$Bolivia$$, $$Bolivia Camiri$$, $$Camiri$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (39, 'marriage agency', $$Bolivia$$, $$Bolivia Cobija$$, $$Cobija$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (40, 'consulat', $$Botswana$$, $$Botswana Francistown$$, $$Francistown$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (41, 'marriage agency', $$Botswana$$, $$Botswana Gaborone$$, $$Gaborone$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (42, 'consulat', $$Brazil$$, $$Brazil Abaetetuba$$, $$Abaetetuba$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (43, 'marriage agency', $$Brazil$$, $$Brazil Acopiara$$, $$Acopiara$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (44, 'consulat', $$Brunei$$, $$Brunei Seria$$, $$Seria$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (45, 'marriage agency', $$Brunei$$, $$Brunei Tutong$$, $$Tutong$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (46, 'consulat', $$Bulgaria$$, $$Bulgaria Asenovgrad$$, $$Asenovgrad$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (47, 'marriage agency', $$Bulgaria$$, $$Bulgaria Aytos$$, $$Aytos$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (48, 'consulat', $$Burundi$$, $$Burundi Bujumbura$$, $$Bujumbura$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (49, 'marriage agency', $$Burundi$$, $$Burundi Bururi$$, $$Bururi$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (50, 'consulat', $$Cambodia$$, $$Cambodia Battambang$$, $$Battambang$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (51, 'marriage agency', $$Cambodia$$, $$Cambodia Kampot$$, $$Kampot$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (52, 'consulat', $$Cameroon$$, $$Cameroon Akonolinga$$, $$Akonolinga$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (53, 'marriage agency', $$Cameroon$$, $$Cameroon Bafang$$, $$Bafang$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (54, 'consulat', $$Canada$$, $$Canada Abbotsford$$, $$Abbotsford$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (55, 'marriage agency', $$Canada$$, $$Canada Airdrie$$, $$Airdrie$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (56, 'consulat', $$Chad$$, $$Chad Ati$$, $$Ati$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (57, 'marriage agency', $$Chad$$, $$Chad Benoy$$, $$Benoy$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (58, 'consulat', $$Chile$$, $$Chile Ancud$$, $$Ancud$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (59, 'marriage agency', $$Chile$$, $$Chile Angol$$, $$Angol$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (60, 'consulat', $$China$$, $$China Acheng$$, $$Acheng$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (61, 'marriage agency', $$China$$, $$China Altay$$, $$Altay$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (62, 'consulat', $$Colombia$$, $$Colombia Aguachica$$, $$Aguachica$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (63, 'marriage agency', $$Colombia$$, $$Colombia Aguadas$$, $$Aguadas$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (64, 'consulat', $$Comoros$$, $$Comoros Moroni$$, $$Moroni$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (65, 'marriage agency', $$Comoros$$, $$Comoros Moutsamoudou$$, $$Moutsamoudou$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (66, 'consulat', $$Croatia$$, $$Croatia Bjelovar$$, $$Bjelovar$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (67, 'marriage agency', $$Croatia$$, $$Croatia Dubrovnik$$, $$Dubrovnik$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (68, 'consulat', $$Cuba$$, $$Cuba Abreus$$, $$Abreus$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (69, 'marriage agency', $$Cuba$$, $$Cuba Alamar$$, $$Alamar$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (70, 'consulat', $$Curacao$$, $$Curacao Willemstad$$, $$Willemstad$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (71, 'consulat', $$Cyprus$$, $$Cyprus Famagusta$$, $$Famagusta$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (72, 'marriage agency', $$Cyprus$$, $$Cyprus Kyrenia$$, $$Kyrenia$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (73, 'consulat', $$Denmark$$, $$Denmark Aabenraa$$, $$Aabenraa$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (74, 'marriage agency', $$Denmark$$, $$Denmark Aalborg$$, $$Aalborg$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (75, 'consulat', $$Djibouti$$, $$Djibouti Djibouti$$, $$Djibouti$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (76, 'marriage agency', $$Djibouti$$, $$Djibouti Obock$$, $$Obock$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (77, 'consulat', $$Dominica$$, $$Dominica Roseau$$, $$Roseau$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (78, 'consulat', $$Ecuador$$, $$Ecuador Ambato$$, $$Ambato$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (79, 'marriage agency', $$Ecuador$$, $$Ecuador Atuntaqui$$, $$Atuntaqui$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (80, 'consulat', $$Egypt$$, $$Egypt Alexandria$$, $$Alexandria$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (81, 'marriage agency', $$Egypt$$, $$Egypt Arish$$, $$Arish$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (82, 'consulat', $$Eritrea$$, $$Eritrea Asmara$$, $$Asmara$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (83, 'marriage agency', $$Eritrea$$, $$Eritrea Assab$$, $$Assab$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (84, 'consulat', $$Estonia$$, $$Estonia Maardu$$, $$Maardu$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (85, 'marriage agency', $$Estonia$$, $$Estonia Narva$$, $$Narva$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (86, 'consulat', $$Ethiopia$$, $$Ethiopia Abomsa$$, $$Abomsa$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (87, 'marriage agency', $$Ethiopia$$, $$Ethiopia Asaita$$, $$Asaita$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (88, 'consulat', $$Fiji$$, $$Fiji Labasa$$, $$Labasa$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (89, 'marriage agency', $$Fiji$$, $$Fiji Lautoka$$, $$Lautoka$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (90, 'consulat', $$Finland$$, $$Finland Anjala$$, $$Anjala$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (91, 'marriage agency', $$Finland$$, $$Finland Espoo$$, $$Espoo$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (92, 'consulat', $$France$$, $$France Abbeville$$, $$Abbeville$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (93, 'marriage agency', $$France$$, $$France Agde$$, $$Agde$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (94, 'consulat', $$Gabon$$, $$Gabon Franceville$$, $$Franceville$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (95, 'marriage agency', $$Gabon$$, $$Gabon Koulamoutou$$, $$Koulamoutou$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (96, 'consulat', $$Gambia$$, $$Gambia Bakau$$, $$Bakau$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (97, 'marriage agency', $$Gambia$$, $$Gambia Banjul$$, $$Banjul$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (98, 'consulat', $$Georgia$$, $$Georgia Akhaltsikhe$$, $$Akhaltsikhe$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (99, 'marriage agency', $$Georgia$$, $$Georgia Batumi$$, $$Batumi$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (100, 'consulat', $$Germany$$, $$Germany Aachen$$, $$Aachen$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (101, 'marriage agency', $$Germany$$, $$Germany Aalen$$, $$Aalen$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (102, 'consulat', $$Ghana$$, $$Ghana Aburi$$, $$Aburi$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (103, 'marriage agency', $$Ghana$$, $$Ghana Accra$$, $$Accra$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (104, 'consulat', $$Gibraltar$$, $$Gibraltar Gibraltar$$, $$Gibraltar$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (105, 'consulat', $$Greece$$, $$Greece Athens$$, $$Athens$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (106, 'marriage agency', $$Greece$$, $$Greece Chios$$, $$Chios$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (107, 'consulat', $$Greenland$$, $$Greenland Nuuk$$, $$Nuuk$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (108, 'consulat', $$Guatemala$$, $$Guatemala Alotenango$$, $$Alotenango$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (109, 'marriage agency', $$Guatemala$$, $$Guatemala Barberena$$, $$Barberena$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (110, 'consulat', $$Guinea$$, $$Guinea Camayenne$$, $$Camayenne$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (111, 'marriage agency', $$Guinea$$, $$Guinea Conakry$$, $$Conakry$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (112, 'consulat', $$Guyana$$, $$Guyana Georgetown$$, $$Georgetown$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (113, 'marriage agency', $$Guyana$$, $$Guyana Linden$$, $$Linden$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (114, 'consulat', $$Haiti$$, $$Haiti Carrefour$$, $$Carrefour$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (115, 'marriage agency', $$Haiti$$, $$Haiti Gonayiv$$, $$Gonayiv$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (116, 'consulat', $$Honduras$$, $$Honduras Choloma$$, $$Choloma$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (117, 'marriage agency', $$Honduras$$, $$Honduras Comayagua$$, $$Comayagua$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (118, 'consulat', $$Hungary$$, $$Hungary Abony$$, $$Abony$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (119, 'marriage agency', $$Hungary$$, $$Hungary Ajka$$, $$Ajka$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (120, 'consulat', $$Iceland$$, $$Iceland Akureyri$$, $$Akureyri$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (121, 'consulat', $$India$$, $$India Abohar$$, $$Abohar$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (122, 'marriage agency', $$India$$, $$India Achalpur$$, $$Achalpur$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (123, 'consulat', $$Indonesia$$, $$Indonesia Abepura$$, $$Abepura$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (124, 'marriage agency', $$Indonesia$$, $$Indonesia Adiwerna$$, $$Adiwerna$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (125, 'consulat', $$Iran$$, $$Iran Abadan$$, $$Abadan$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (126, 'marriage agency', $$Iran$$, $$Iran Abhar$$, $$Abhar$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (127, 'consulat', $$Iraq$$, $$Iraq Baghdad$$, $$Baghdad$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (128, 'marriage agency', $$Iraq$$, $$Iraq Balad$$, $$Balad$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (129, 'consulat', $$Ireland$$, $$Ireland Athlone$$, $$Athlone$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (130, 'marriage agency', $$Ireland$$, $$Ireland Balbriggan$$, $$Balbriggan$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (131, 'consulat', $$Israel$$, $$Israel Ariel$$, $$Ariel$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (132, 'marriage agency', $$Israel$$, $$Israel Ashdod$$, $$Ashdod$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (133, 'consulat', $$Italy$$, $$Italy Abbiategrasso$$, $$Abbiategrasso$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (134, 'marriage agency', $$Italy$$, $$Italy Acerra$$, $$Acerra$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (135, 'consulat', $$Jamaica$$, $$Jamaica Kingston$$, $$Kingston$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (136, 'marriage agency', $$Jamaica$$, $$Jamaica Linstead$$, $$Linstead$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (137, 'consulat', $$Japan$$, $$Japan Abashiri$$, $$Abashiri$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (138, 'marriage agency', $$Japan$$, $$Japan Abiko$$, $$Abiko$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (139, 'consulat', $$Jordan$$, $$Jordan Amman$$, $$Amman$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (140, 'marriage agency', $$Jordan$$, $$Jordan Aqaba$$, $$Aqaba$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (141, 'consulat', $$Kazakhstan$$, $$Kazakhstan Abay$$, $$Abay$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (142, 'marriage agency', $$Kazakhstan$$, $$Kazakhstan Aksu$$, $$Aksu$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (143, 'consulat', $$Kenya$$, $$Kenya Bungoma$$, $$Bungoma$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (144, 'marriage agency', $$Kenya$$, $$Kenya Busia$$, $$Busia$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (145, 'consulat', $$Kiribati$$, $$Kiribati Tarawa$$, $$Tarawa$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (146, 'consulat', $$Kosovo$$, $$Kosovo Dragash$$, $$Dragash$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (147, 'marriage agency', $$Kosovo$$, $$Kosovo Ferizaj$$, $$Ferizaj$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (148, 'consulat', $$Kyrgyzstan$$, $$Kyrgyzstan Balykchy$$, $$Balykchy$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (149, 'marriage agency', $$Kyrgyzstan$$, $$Kyrgyzstan Bishkek$$, $$Bishkek$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (150, 'consulat', $$Laos$$, $$Laos Phonsavan$$, $$Phonsavan$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (151, 'marriage agency', $$Laos$$, $$Laos Vangviang$$, $$Vangviang$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (152, 'consulat', $$Latvia$$, $$Latvia Daugavpils$$, $$Daugavpils$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (153, 'marriage agency', $$Latvia$$, $$Latvia Jelgava$$, $$Jelgava$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (154, 'consulat', $$Lebanon$$, $$Lebanon Baalbek$$, $$Baalbek$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (155, 'marriage agency', $$Lebanon$$, $$Lebanon Beirut$$, $$Beirut$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (156, 'consulat', $$Lesotho$$, $$Lesotho Leribe$$, $$Leribe$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (157, 'marriage agency', $$Lesotho$$, $$Lesotho Mafeteng$$, $$Mafeteng$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (158, 'consulat', $$Liberia$$, $$Liberia Bensonville$$, $$Bensonville$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (159, 'marriage agency', $$Liberia$$, $$Liberia Buchanan$$, $$Buchanan$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (160, 'consulat', $$Libya$$, $$Libya Ajdabiya$$, $$Ajdabiya$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (161, 'marriage agency', $$Libya$$, $$Libya Benghazi$$, $$Benghazi$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (162, 'consulat', $$Liechtenstein$$, $$Liechtenstein Vaduz$$, $$Vaduz$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (163, 'consulat', $$Lithuania$$, $$Lithuania Aleksotas$$, $$Aleksotas$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (164, 'marriage agency', $$Lithuania$$, $$Lithuania Alytus$$, $$Alytus$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (165, 'consulat', $$Luxembourg$$, $$Luxembourg Dudelange$$, $$Dudelange$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (166, 'marriage agency', $$Luxembourg$$, $$Luxembourg Luxembourg$$, $$Luxembourg$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (167, 'consulat', $$Macao$$, $$Macao Macau$$, $$Macau$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (168, 'consulat', $$Macedonia$$, $$Macedonia Bitola$$, $$Bitola$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (169, 'marriage agency', $$Macedonia$$, $$Macedonia Bogovinje$$, $$Bogovinje$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (170, 'consulat', $$Madagascar$$, $$Madagascar Alarobia$$, $$Alarobia$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (171, 'marriage agency', $$Madagascar$$, $$Madagascar Ambalavao$$, $$Ambalavao$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (172, 'consulat', $$Malawi$$, $$Malawi Balaka$$, $$Balaka$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (173, 'marriage agency', $$Malawi$$, $$Malawi Blantyre$$, $$Blantyre$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (174, 'consulat', $$Malaysia$$, $$Malaysia Bahau$$, $$Bahau$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (175, 'marriage agency', $$Malaysia$$, $$Malaysia Bakri$$, $$Bakri$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (176, 'consulat', $$Maldives$$, $$Maldives Male$$, $$Male$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (177, 'consulat', $$Mali$$, $$Mali Bamako$$, $$Bamako$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (178, 'marriage agency', $$Mali$$, $$Mali Banamba$$, $$Banamba$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (179, 'consulat', $$Malta$$, $$Malta Birkirkara$$, $$Birkirkara$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (180, 'marriage agency', $$Malta$$, $$Malta Mosta$$, $$Mosta$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (181, 'consulat', $$Martinique$$, $$Martinique Ducos$$, $$Ducos$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (182, 'consulat', $$Mauritania$$, $$Mauritania Aleg$$, $$Aleg$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (183, 'marriage agency', $$Mauritania$$, $$Mauritania Atar$$, $$Atar$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (184, 'consulat', $$Mauritius$$, $$Mauritius Curepipe$$, $$Curepipe$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (185, 'marriage agency', $$Mauritius$$, $$Mauritius Goodlands$$, $$Goodlands$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (186, 'consulat', $$Mayotte$$, $$Mayotte Dzaoudzi$$, $$Dzaoudzi$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (187, 'marriage agency', $$Mayotte$$, $$Mayotte Koungou$$, $$Koungou$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (188, 'consulat', $$Mexico$$, $$Mexico Abasolo$$, $$Abasolo$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (189, 'marriage agency', $$Mexico$$, $$Mexico Acajete$$, $$Acajete$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (190, 'consulat', $$Moldova$$, $$Moldova Bender$$, $$Bender$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (191, 'marriage agency', $$Moldova$$, $$Moldova Cahul$$, $$Cahul$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (192, 'consulat', $$Monaco$$, $$Monaco Monaco$$, $$Monaco$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (193, 'consulat', $$Mongolia$$, $$Mongolia Altai$$, $$Altai$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (194, 'marriage agency', $$Mongolia$$, $$Mongolia Arvayheer$$, $$Arvayheer$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (195, 'consulat', $$Montenegro$$, $$Montenegro Bar$$, $$Bar$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (196, 'marriage agency', $$Montenegro$$, $$Montenegro Budva$$, $$Budva$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (197, 'consulat', $$Montserrat$$, $$Montserrat Brades$$, $$Brades$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (198, 'marriage agency', $$Montserrat$$, $$Montserrat Plymouth$$, $$Plymouth$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (199, 'consulat', $$Morocco$$, $$Morocco Agadir$$, $$Agadir$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (200, 'marriage agency', $$Morocco$$, $$Morocco Ahfir$$, $$Ahfir$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (201, 'consulat', $$Mozambique$$, $$Mozambique Beira$$, $$Beira$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (202, 'marriage agency', $$Mozambique$$, $$Mozambique Chibuto$$, $$Chibuto$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (203, 'consulat', $$Myanmar$$, $$Myanmar Bago$$, $$Bago$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (204, 'marriage agency', $$Myanmar$$, $$Myanmar Bhamo$$, $$Bhamo$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (205, 'consulat', $$Namibia$$, $$Namibia Gobabis$$, $$Gobabis$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (206, 'marriage agency', $$Namibia$$, $$Namibia Grootfontein$$, $$Grootfontein$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (207, 'consulat', $$Nauru$$, $$Nauru Yaren$$, $$Yaren$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (208, 'consulat', $$Nepal$$, $$Nepal Bhadrapur$$, $$Bhadrapur$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (209, 'marriage agency', $$Nepal$$, $$Nepal Bharatpur$$, $$Bharatpur$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (210, 'consulat', $$Netherlands$$, $$Netherlands Aalsmeer$$, $$Aalsmeer$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (211, 'marriage agency', $$Netherlands$$, $$Netherlands Aalten$$, $$Aalten$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (212, 'consulat', $$Nicaragua$$, $$Nicaragua Bluefields$$, $$Bluefields$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (213, 'marriage agency', $$Nicaragua$$, $$Nicaragua Boaco$$, $$Boaco$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (214, 'consulat', $$Niger$$, $$Niger Agadez$$, $$Agadez$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (215, 'marriage agency', $$Niger$$, $$Niger Alaghsas$$, $$Alaghsas$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (216, 'consulat', $$Nigeria$$, $$Nigeria Aba$$, $$Aba$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (217, 'marriage agency', $$Nigeria$$, $$Nigeria Abakaliki$$, $$Abakaliki$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (218, 'consulat', $$Niue$$, $$Niue Alofi$$, $$Alofi$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (219, 'consulat', $$Norway$$, $$Norway Arendal$$, $$Arendal$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (220, 'marriage agency', $$Norway$$, $$Norway Bergen$$, $$Bergen$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (221, 'consulat', $$Oman$$, $$Oman Bawshar$$, $$Bawshar$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (222, 'marriage agency', $$Oman$$, $$Oman Bidbid$$, $$Bidbid$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (223, 'consulat', $$Pakistan$$, $$Pakistan Akora$$, $$Akora$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (224, 'marriage agency', $$Pakistan$$, $$Pakistan Amangarh$$, $$Amangarh$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (225, 'consulat', $$Palau$$, $$Palau Melekeok$$, $$Melekeok$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (226, 'consulat', $$Panama$$, $$Panama Aguadulce$$, $$Aguadulce$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (227, 'marriage agency', $$Panama$$, $$Panama Changuinola$$, $$Changuinola$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (228, 'consulat', $$Paraguay$$, $$Paraguay Limpio$$, $$Limpio$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (229, 'marriage agency', $$Paraguay$$, $$Paraguay Nemby$$, $$Nemby$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (230, 'consulat', $$Peru$$, $$Peru Abancay$$, $$Abancay$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (231, 'marriage agency', $$Peru$$, $$Peru Andahuaylas$$, $$Andahuaylas$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (232, 'consulat', $$Philippines$$, $$Philippines Abucay$$, $$Abucay$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (233, 'marriage agency', $$Philippines$$, $$Philippines Abuyog$$, $$Abuyog$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (234, 'consulat', $$Pitcairn$$, $$Pitcairn Adamstown$$, $$Adamstown$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (235, 'consulat', $$Poland$$, $$Poland Bartoszyce$$, $$Bartoszyce$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (236, 'marriage agency', $$Poland$$, $$Poland Bemowo$$, $$Bemowo$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (237, 'consulat', $$Portugal$$, $$Portugal Albufeira$$, $$Albufeira$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (238, 'marriage agency', $$Portugal$$, $$Portugal Alcabideche$$, $$Alcabideche$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (239, 'consulat', $$Qatar$$, $$Qatar Doha$$, $$Doha$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (240, 'consulat', $$Romania$$, $$Romania Adjud$$, $$Adjud$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (241, 'marriage agency', $$Romania$$, $$Romania Aiud$$, $$Aiud$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (242, 'consulat', $$Russia$$, $$Russia Abakan$$, $$Abakan$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (243, 'marriage agency', $$Russia$$, $$Russia Abaza$$, $$Abaza$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (244, 'consulat', $$Rwanda$$, $$Rwanda Butare$$, $$Butare$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (245, 'marriage agency', $$Rwanda$$, $$Rwanda Byumba$$, $$Byumba$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (246, 'consulat', $$Samoa$$, $$Samoa Apia$$, $$Apia$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (247, 'consulat', $$Senegal$$, $$Senegal Bignona$$, $$Bignona$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (248, 'marriage agency', $$Senegal$$, $$Senegal Dakar$$, $$Dakar$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (249, 'consulat', $$Serbia$$, $$Serbia Apatin$$, $$Apatin$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (250, 'marriage agency', $$Serbia$$, $$Serbia Belgrade$$, $$Belgrade$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (251, 'consulat', $$Seychelles$$, $$Seychelles Victoria$$, $$Victoria$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (252, 'consulat', $$Singapore$$, $$Singapore Singapore$$, $$Singapore$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (253, 'consulat', $$Slovakia$$, $$Slovakia Bardejov$$, $$Bardejov$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (254, 'marriage agency', $$Slovakia$$, $$Slovakia Bratislava$$, $$Bratislava$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (255, 'consulat', $$Slovenia$$, $$Slovenia Celje$$, $$Celje$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (256, 'marriage agency', $$Slovenia$$, $$Slovenia Koper$$, $$Koper$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (257, 'consulat', $$Somalia$$, $$Somalia Afgooye$$, $$Afgooye$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (258, 'marriage agency', $$Somalia$$, $$Somalia Baardheere$$, $$Baardheere$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (259, 'consulat', $$Spain$$, $$Spain Adeje$$, $$Adeje$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (260, 'marriage agency', $$Spain$$, $$Spain Adra$$, $$Adra$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (261, 'consulat', $$Sudan$$, $$Sudan Atbara$$, $$Atbara$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (262, 'marriage agency', $$Sudan$$, $$Sudan Berber$$, $$Berber$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (263, 'consulat', $$Suriname$$, $$Suriname Lelydorp$$, $$Lelydorp$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (264, 'marriage agency', $$Suriname$$, $$Suriname Paramaribo$$, $$Paramaribo$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (265, 'consulat', $$Swaziland$$, $$Swaziland Lobamba$$, $$Lobamba$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (266, 'marriage agency', $$Swaziland$$, $$Swaziland Manzini$$, $$Manzini$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (267, 'consulat', $$Sweden$$, $$Sweden Boden$$, $$Boden$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (268, 'marriage agency', $$Sweden$$, $$Sweden Boo$$, $$Boo$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (269, 'consulat', $$Switzerland$$, $$Switzerland Aarau$$, $$Aarau$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (270, 'marriage agency', $$Switzerland$$, $$Switzerland Adliswil$$, $$Adliswil$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (271, 'consulat', $$Syria$$, $$Syria Aleppo$$, $$Aleppo$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (272, 'marriage agency', $$Syria$$, $$Syria Binnish$$, $$Binnish$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (273, 'consulat', $$Taiwan$$, $$Taiwan Banqiao$$, $$Banqiao$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (274, 'marriage agency', $$Taiwan$$, $$Taiwan Daxi$$, $$Daxi$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (275, 'consulat', $$Tajikistan$$, $$Tajikistan Boshkengash$$, $$Boshkengash$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (276, 'marriage agency', $$Tajikistan$$, $$Tajikistan Chkalov$$, $$Chkalov$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (277, 'consulat', $$Tanzania$$, $$Tanzania Arusha$$, $$Arusha$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (278, 'marriage agency', $$Tanzania$$, $$Tanzania Babati$$, $$Babati$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (279, 'consulat', $$Thailand$$, $$Thailand Aranyaprathet$$, $$Aranyaprathet$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (280, 'marriage agency', $$Thailand$$, $$Thailand Bangkok$$, $$Bangkok$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (281, 'consulat', $$Togo$$, $$Togo Badou$$, $$Badou$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (282, 'marriage agency', $$Togo$$, $$Togo Bafilo$$, $$Bafilo$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (283, 'consulat', $$Tunisia$$, $$Tunisia Akouda$$, $$Akouda$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (284, 'marriage agency', $$Tunisia$$, $$Tunisia Ariana$$, $$Ariana$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (285, 'consulat', $$Turkey$$, $$Turkey Adana$$, $$Adana$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (286, 'marriage agency', $$Turkey$$, $$Turkey Adilcevaz$$, $$Adilcevaz$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (287, 'consulat', $$Turkmenistan$$, $$Turkmenistan Abadan$$, $$Abadan$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (288, 'marriage agency', $$Turkmenistan$$, $$Turkmenistan Annau$$, $$Annau$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (289, 'consulat', $$Tuvalu$$, $$Tuvalu Funafuti$$, $$Funafuti$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (290, 'consulat', $$Uganda$$, $$Uganda Adjumani$$, $$Adjumani$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (291, 'marriage agency', $$Uganda$$, $$Uganda Arua$$, $$Arua$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (292, 'consulat', $$Ukraine$$, $$Ukraine Alushta$$, $$Alushta$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (293, 'marriage agency', $$Ukraine$$, $$Ukraine Amvrosiyivka$$, $$Amvrosiyivka$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (294, 'consulat', $$Uruguay$$, $$Uruguay Artigas$$, $$Artigas$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (295, 'marriage agency', $$Uruguay$$, $$Uruguay Canelones$$, $$Canelones$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (296, 'consulat', $$Uzbekistan$$, $$Uzbekistan Andijon$$, $$Andijon$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (297, 'marriage agency', $$Uzbekistan$$, $$Uzbekistan Angren$$, $$Angren$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (298, 'consulat', $$Venezuela$$, $$Venezuela Acarigua$$, $$Acarigua$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (299, 'marriage agency', $$Venezuela$$, $$Venezuela Anaco$$, $$Anaco$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (300, 'consulat', $$Vietnam$$, $$Vietnam Haiphong$$, $$Haiphong$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (301, 'marriage agency', $$Vietnam$$, $$Vietnam Hanoi$$, $$Hanoi$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (302, 'consulat', $$Yemen$$, $$Yemen Aden$$, $$Aden$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (303, 'marriage agency', $$Yemen$$, $$Yemen Ataq$$, $$Ataq$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (304, 'consulat', $$Zambia$$, $$Zambia Chililabombwe$$, $$Chililabombwe$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (305, 'marriage agency', $$Zambia$$, $$Zambia Chingola$$, $$Chingola$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (306, 'consulat', $$Zimbabwe$$, $$Zimbabwe Beitbridge$$, $$Beitbridge$$);
INSERT INTO offices (id, office_type, country, address, city) VALUES (307, 'marriage agency', $$Zimbabwe$$, $$Zimbabwe Bindura$$, $$Bindura$$);
